server:
  port: 9090

spring:
  # =============DataSource=============
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/code_snippet?useUnicode=true&characterEncoding=utf-8&userSSL=false
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: code-snippet
      connection-timeout: 10000
mybatis:
  mapper-locations: classpath:mapper/*.xml
