spring:
  application:
    name: 05-springboot-nacos
  config:
    import:
      # 动态配置导入
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      # nacos控制台配置用户名、密码
      username: nacos
      password: nacos
      config:
        server-addr: 192.168.1.3:8848
        group: DEFAULT_GROUP
        namespace: 5ad46001-785d-49b6-be13-d0cb7d78ced0
        refresh-enabled: true
        enable-remote-sync-config: true
        file-extension: yaml
      discovery:
        server-addr: 192.168.1.3:8848
        service: springboot-nacos-test
        namespace: 5ad46001-785d-49b6-be13-d0cb7d78ced0
        group: DEFAULT_GROUP

server:
  port: 9191
