spring:
  application:
    name: dubbo-consumer
server:
  port: 8080
dubbo:
  application:
    name: dubbo-consumer
    logger: slf4j
    shut-wait: 10s
    qos-port: 22221
  protocol:
    name: tri
    port: -1
  registry:
    register: true
    address: nacos://192.168.1.3:8848?namespace=2d7ea377-de1a-4496-9920-fa4c5c6a65e5
    register-mode: instance
